name: ethereum_multicall
description: Multicall allows multiple smart contract constant function calls to be grouped into a single call and the results aggregated into a single result
version: 1.0.2
homepage: https://wakumo.vn
repository: https://github.com/wakumo/ethereum-multicall

environment:
  sdk: ^3.3.0

dependencies:
  web3dart: ^2.3.3
  collection: ^1.15.0
  http: ^0.13.6

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
